reveal-py:
    slides:
        separator: ^\s*---\s*$
        verticalSeparator: ^\s*-v-\s*$
        # notes: "^Notes+:"
        # charset: iso-8859-15
        theme: theme.css
        highlight-theme: vs
        # template
    index:
        title: "Reveal-py"
        theme: assets/styles/index.css
        # template
    # css: <files>
    # scripts: <files>
    # host: <host>
    # port: <port>
    # featured-slide: <num>
reveal.js:
    width: 1920
    height: 1080
    transition: fade
