reveal-py:
    per-slide:
        separator: ^\s*---\s*$
        verticalSeparator: ^\s*-v-\s*$
        # notes: "^Notes+:"
        # charset: iso-8859-15
    index:
        title: "Index"
        theme: assets/styles/index.css
    global:
        theme: theme.css
        highlight-theme: vs
    # css: <files>
    # scripts: <files>
    # template: <filename>
    # listing-template: <filename>
    # host: <host>
    # port: <port>
    # featured-slide: <num>
reveal.js:
    width: 1920
    height: 1080
    transition: fade
