[tool.poetry]
name = "MkSlides-Reveal"
version = "0.1.0"
description = "MkSlides-Reveal - Slides with Markdown using the power of Reveal.js."
authors = ["MartenBE <https://github.com/MartenBE>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "mkslides-reveal", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
Jinja2 = "^3.1.4"
livereload = "^2.7.0"
python-frontmatter = "^1.1.0"
PyYAML = "^6.0.2"
rich = "^13.8.0"

[tool.poetry.group.dev.dependencies]
bumpver = "^2023.1129"
black = "^24.8.0"

[tool.poetry.scripts]
mkslides-reveal = "mkslides-reveal.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bumpver]
current_version = "2024.1001-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"README.md" = [
    "{version}",
    "{pep440_version}",
]

